### ISSUE TITLE
Test all feature combinations in CI

### ISSUE THREAD

**Issue by alice-i-cecile** [Leafwing-Studios/leafwing-input-manager#199]
## What problem does this solve?

We're using features to enable and disable various parts of the library. However  Ci only checks one combination.

## What solution would you like?

Check more feature combinations in CI. This could be done combinatorially, one at a time or just by checking the no features combination.

The last choice is probably the best ROI for now.

**Comment by it-me-joda** [comment]
As of right now, the CI check_tests currently runs:
- no features
- default features
- default features + timing
- default features + asset

This effectively covers most use cases. We could run all features combinatorially. The only downside is that it will take much longer to run the check_tests step especially as code coverage increases.

For completeness here is all the features:
```toml
[features]
default = ["asset", "ui", "mouse", "keyboard", "gamepad", "picking"]

# Allow support for tracking timing information about actions (how long a button was pressed, etc.)
timing = []

# Adds support for mouse-based inputs.
mouse = []

# Adds support for keyboard-based inputs.
keyboard = []

# Adds support for gamepad-based inputs.
gamepad = ["bevy/bevy_gilrs"]

# Allow using the `InputMap` as `bevy::asset::Asset`.
asset = ['bevy/bevy_asset']

# Add support for 'bevy::ui' integration:
# - Allow 'bevy::ui' to take priority over actions when processing inputs.
ui = ['bevy/bevy_ui']

# Add support for 'bevy::picking' integration:
# - Order systems to allow picking observers to modify action state.
picking = ['bevy/bevy_picking']

# Enable winit platforms to ensure that docs.rs builds correctly
# Users should never need to enable this feature
docs = ['winit/x11', 'winit/wayland']
```
